config/routes.rb
New1::Application.routes.draw do
  resources :joinposts

  get "comments/create"

  get "comments/destroy"

  devise_for :users do
    resources :posts do 
      resources :comments
    end
    end
  root to: "posts#index"

end

app/models/joinpost.rb
class Joinpost < ActiveRecord::Base
  attr_accessible :name, :post
end

app/controllers/joinposts_controller.rb
class JoinpostsController < ApplicationController
  # GET /joinposts
  # GET /joinposts.json
  def index
    @joinposts = Joinpost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @joinposts }
    end
  end

  # GET /joinposts/1
  # GET /joinposts/1.json
  def show
    @joinpost = Joinpost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @joinpost }
    end
  end

  # GET /joinposts/new
  # GET /joinposts/new.json
  def new
    @joinpost = Joinpost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @joinpost }
    end
  end

  # GET /joinposts/1/edit
  def edit
    @joinpost = Joinpost.find(params[:id])
  end

  # POST /joinposts
  # POST /joinposts.json
  def create
    @joinpost = Joinpost.new(params[:joinpost])

    respond_to do |format|
      if @joinpost.save
        format.html { redirect_to @joinpost, notice: 'Joinpost was successfully created.' }
        format.json { render json: @joinpost, status: :created, location: @joinpost }
      else
        format.html { render action: "new" }
        format.json { render json: @joinpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /joinposts/1
  # PUT /joinposts/1.json
  def update
    @joinpost = Joinpost.find(params[:id])

    respond_to do |format|
      if @joinpost.update_attributes(params[:joinpost])
        format.html { redirect_to @joinpost, notice: 'Joinpost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @joinpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joinposts/1
  # DELETE /joinposts/1.json
  def destroy
    @joinpost = Joinpost.find(params[:id])
    @joinpost.destroy

    respond_to do |format|
      format.html { redirect_to joinposts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/joinposts_helper.rb
module JoinpostsHelper
end

app/views/joinposts/_form.html.erb
<%= form_for(@joinpost) do |f| %>
  <% if @joinpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@joinpost.errors.count, "error") %> prohibited this joinpost from being saved:</h2>

      <ul>
      <% @joinpost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/joinposts/edit.html.erb
<h1>Editing joinpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @joinpost %> |
<%= link_to 'Back', joinposts_path %>

app/views/joinposts/index.html.erb
<h1>Listing joinposts</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @joinposts.each do |joinpost| %>
  <tr>
    <td><%= joinpost.post %></td>
    <td><%= joinpost.name %></td>
    <td><%= link_to 'Show', joinpost %></td>
    <td><%= link_to 'Edit', edit_joinpost_path(joinpost) %></td>
    <td><%= link_to 'Destroy', joinpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Joinpost', new_joinpost_path %>

app/views/joinposts/new.html.erb
<h1>New joinpost</h1>

<%= render 'form' %>

<%= link_to 'Back', joinposts_path %>

app/views/joinposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @joinpost.post %>
</p>

<p>
  <b>Name:</b>
  <%= @joinpost.name %>
</p>


<%= link_to 'Edit', edit_joinpost_path(@joinpost) %> |
<%= link_to 'Back', joinposts_path %>