config/routes.rb
New1::Application.routes.draw do
  resources :joinposts

  get "comments/create"

  get "comments/destroy"

  devise_for :users do
    resources :posts do 
      resources :comments
    end
    end
  root to: "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title

  #validates :name,  :presence => true
  validates :title, :presence => true,
		    :length => { :minimum => 5 }

  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:update, :create, :destroy, :new, :edit]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post1 = Post.last
    @post2 = Post.order("created_at DESC").limit(1).offset(1).last
    @post3 = Post.order("created_at DESC").limit(1).offset(2).last
    @post4 = Post.order("created_at DESC").limit(1).offset(3).last
    @post5 = Post.order("created_at DESC").limit(1).offset(4).last
    @post6 = Post.order("created_at DESC").limit(1).offset(5).last

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    if current_user.try(:admin?)
        respond_to do |format|

            format.html # new.html.erb
            format.json { render json: @post }
        end
    else 
      flash[:error] = "You don't have permission to create new post"
      redirect_to posts_path
    end
  end

  # GET /posts/1/edit
  def edit
      if current_user.try(:admin?)
        @post = Post.find(params[:id])
      else
        redirect_to posts_path
       end 
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
      end
    end
  end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, html: { class: 'form-vertical'}) do |f| %>
  <fieldset>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="controller-group">
    <br /><%= f.label :title %>
    <div class='control row-fluid'>
      <%= f.text_field :title, class: 'span12'  %>
    </div>
  </div>
  <div class="controller-group">
      <div class='control row-fluid'>
      </div>
    <br /><%= f.label :Detail %>
    <%= f.text_area :body, class: 'span11' %>
  </div>

    <span class='pull-right'>
      <%= link_to 'Back', posts_path, class: 'btn btn-primary' %>
      <%= f.submit class: 'btn btn-primary' %>
    </span>

  </fieldset>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
   <div class="hero-unit hidden-phone">

		<h1>Editing post</h1>

		<%= render 'form' %>

	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
<!-- Head Slide show -->
      <div class="hero-unit">
        <div id="myCarousel" class="carousel slide">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>s
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <!-- Carousel items -->
      <div class="carousel-inner">
        <div class="active item"><%= image_tag("HeadPic1.jpg") %></div>
        <div class="item"><%= image_tag("HeadPic2.jpg") %></div>
        <div class="item"><%= image_tag("HeadPic3.jpg") %></div>
      </div>
      <!-- Carousel nav -->
      <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
<!-- End Head Slide show -->

<!-- Show last post -->
    <div class="well">
       <!-- Show Large Newest posts -->
      <h3>
        <%= @post1.title %><a href="/posts/ <%= @post1.id %>" class='btn pull-right btn-small btn-inverse'><i class='icon-zoom-in'></i> See more >></a>
      </h3>
      <p>
        <%= truncate( @post1.body , :length => 600, :separator => ' ') %>
      </p>
    </div>
<!-- End Show Large Newest posts -->

<!-- Show last post 3 colum -->
    <div class="row-fluid">
      <div class="span4">
        <h4>
          <a href="/posts/ <%= @post2.id %>" class='btn pull-right btn-small btn-warning'><i class='icon-zoom-in'></i></a>
          <%= @post2.title %>      
        </h4>
        <p>
          <%= truncate( @post2.body , :length => 200, :separator => ' ') %>
        </p>
      </div>
      <div class="span4">
        <h4>
          <a href="/posts/ <%= @post3.id %>" class='btn pull-right btn-small btn-warning'><i class='icon-zoom-in'></i></a>
          <%= @post3.title %>  
        </h4>
        <p>
          <%= truncate( @post3.body , :length => 200, :separator => ' ') %>
        </p>
      </div>
      <div class="span4">
        <h4>
          <a href="/posts/ <%= @post4.id %>" class='btn pull-right btn-small btn-warning'><i class='icon-zoom-in'></i></a>
          <%= @post4.title %>
        </h4>
        <p>
          <%= truncate( @post4.body , :length => 200, :separator => ' ') %>  
        </p>
      </div>
    </div>    
<!-- End Show last post 3 colum -->
    </div>


        <!-- Show box login&regist -->
    <div class="row main-features">
      <div class="span6">
        <div class="well">
          <h3>Member Register</h3>
          <p>Subscribe this website.
          </br> </br> 
          </p>
          <a class="btn btn-info" href="/users/sign_up">Click to register<br></a> 
        </div>
      </div>

      <div class="span6">
        <div class="well">
          <h3>Member Login</h3>
          <p>Is you have an account member, Please login, </br>So that use your rights to
              the fullest.</p>
          <a class="btn btn-success" href="/users/sign_in">Click to login</a> 
        </div>
      </div>

    </div>
        <!-- end of Show box login&regist -->

<!--  Status
    <div class="container">
      <div class='container-fluid'>
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%=name == :notice ? 'success' : 'error' %>">
            <a class='close' data-dismiss="alert">x</a>
          <%= msg %>
          </div>
        <% end %> 
      <%= yield %>
    </div>  
-->
    <div class="hero-unit hidden-phone">
      <h2>Listing posts You Know Blog! </h2>
      <ul class='main-list well'>
      <% @posts.each do |post| %>
      <li class='row-fluid'>
        <div class='span6'><%= post.title %></div>
          <div class='pull-right'>
            <a href="/posts/ <%= post.id %>" class='btn primary btn-small'><i class='icon-zoom-in'></i> Show</a>
            <% if current_user.try(:admin?) %>
            <a href="/posts/ <%= post.id %>/edit" class='btn btn-warning btn-small'><i class='icon-edit'></i> Edit</a>
            <a href="<%= post_path(post) %>" class='btn btn-danger btn-small'data-confirm='Are you sure?' data-method='delete' rel='nofollow'><i class='icon-remove'></i>Destroy</a>
            <% end %>
          </div>
        </li>
      <% end %>
      <% if current_user.try(:admin?) %>
        <a href= '/posts/new' class='btn btn-success btn-small pull-right'><i class='icon-plus'></i> New Post</a>
      <% end %>
    </div>

  <!-- Alert -->
  <div class="alert alert-success">
    <h5>Create by:</h5>
    iChoo@iPv6</br>
    www.9Choo.in.th
  </div>
  <!-- End of Alert -->

</div>

app/views/posts/new.html.erb
<div class="container">
   <div class="hero-unit hidden-phone">
   	<h2>New post</h2>

		<%= render 'form' %>

	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
   <div class="hero-unit hidden-phone">

		<% if current_user.try(:admin?) %>
        	<%= link_to "Edit Post",edit_post_path(@post), class: 'btn btn-warning pull-right' %>
    	<% end %>
      	<h2>
          <b>Post:</b>
          <%= @post.title %>
      	</h2>
     	 <%= @post.body %>
      	</br></br>

		-------------------------------------------------------------------
		<h4>Comment :</h4>
		<% @post.comments.each do |comment| %>
		  	<p><b><%= comment.body %></b></p>
		  	<p>By : <%= comment.commenter %></p>
		  	<p><i>Create comment: <%= comment.created_at %> 
		  		(<%= time_ago_in_words comment.created_at %> ago)</i>
		  	</p>
		<% end %>

		-------------------------------------------------------------------
		<% if current_user %>
			<h4>Add a Comment:</h4>
				<%= render "comments/form" %>
			</br>
			<%= link_to "Back",posts_path, class: 'btn btn-success pull-right' %>
		<% end %>
	</div>	      	
</div>